name: Minimal-Block
description: Minimalistic, friendly, responsive.
url: http://yoursite.com
markdown: redcarpet
paginate: 8
highlighter: pygments

rss-feed-limit: 10

disqus-id: sdogruyol
twitter: sdogruyol
github: sdogruyol

permalink: /:title