name: Serdar Dogruyol
description: Minimalistic, friendly, responsive.
url: http://serdardogruyol.com
markdown: redcarpet
paginate: 8
highlighter: pygments

rss-feed-limit: 10

disqus-id: serdardogruyol.com
twitter: sdogruyol
github: sdogruyol

permalink: /:title