name: Serdar Dogruyol
description: Ruby, Rails and Software
url: http://serdardogruyol.com
markdown: redcarpet
paginate: 8
highlighter: pygments

rss-feed-limit: 10

twitter: sdogruyol
github: sdogruyol

permalink: /:title

gems:
  - jekyll-redirect-from
